// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_2JUjHtYJUQ8M71fwFeWzNUq2fHEHLsU',
    appId: '1:1072271780445:web:0c71f084d34a62cd2abbb4',
    messagingSenderId: '1072271780445',
    projectId: 'omar-22746',
    authDomain: 'omar-22746.firebaseapp.com',
    storageBucket: 'omar-22746.appspot.com',
    measurementId: 'G-JHTY4K03D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGrbw0CT4e5s5FFzVA5Wyu6OD0KXhOT4',
    appId: '1:1072271780445:android:9098aaecc192d79f2abbb4',
    messagingSenderId: '1072271780445',
    projectId: 'omar-22746',
    storageBucket: 'omar-22746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwU4jbX-FX4AVsM7xIxErZk1E9NPtNlY',
    appId: '1:1072271780445:ios:874c6168f73a7ec52abbb4',
    messagingSenderId: '1072271780445',
    projectId: 'omar-22746',
    storageBucket: 'omar-22746.appspot.com',
    iosClientId: '1072271780445-02cdnb5j33o3tetrjpk5nktc08sdsdp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwU4jbX-FX4AVsM7xIxErZk1E9NPtNlY',
    appId: '1:1072271780445:ios:052aa3a951c8aad12abbb4',
    messagingSenderId: '1072271780445',
    projectId: 'omar-22746',
    storageBucket: 'omar-22746.appspot.com',
    iosClientId: '1072271780445-bblb50mdmml22pfo07vbqb3gs85u1305.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
